### ISSUE TITLE
Add how to on using a private account 

### ISSUE THREAD

**Issue by wxcafe** [tootsuite/documentation#109]
see tootsuite/mastodon#2187

**Comment by expenses** [comment]
It would be also worth documenting how the follow system is implemented as well, I'm not sure [my comment](https://github.com/tootsuite/mastodon/issues/2187#issuecomment-295570459) in the referenced post is accurate at all.

**Comment by dariusk** [comment]
Mostly addressed in #121 which was just merged. Closing this!
