### ISSUE TITLE
Extend localization to  ISO 639-2

### ISSUE THREAD

**Issue by belkacem77** [tootsuite/documentation#139]
Hello,
I noticed that the localization is only limited to  languages  in ISO 639-1.
Would you like extend localization to  ISO 639-2. We would like localize Mastodon into Kabyle.

Regrads,

M.Belkacem
Kabyle localizer

**Comment by Artoria2e5** [comment]
Subscribing as I've seen requests for lzh, wuu, and yue. This may involve some PRs to react-intl and rails-i18n as mentioned [here](https://github.com/tootsuite/documentation/blob/master/Contributing-to-Mastodon/Translating.md#appendix-a-plural-handling).

**Comment by yookoala** [comment]
@belkacem77: i18n can be seen as 2 problems:

1. Browser accepted language and server auto-detection.
2. User preference overrides.

Problem (1) has more to do with browser. Do they provide options for you to select your language (e.g. `kab`) and pass as [Accepted-Language](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language) with HTTP header. I think the source code of Mastodon doesn't stop ISO 639-2 country code from working if browsers support it well.

Also Mastodon source code has no limitation on the format of user language preference. Therefore problem (2) is also not an issue.

What could appear to be an issue is modifying [mastodon.js](https://github.com/tootsuite/mastodon/blob/ca05bfaac7894285bf9ebbfeebe8c379b94eeb42/app/javascript/mastodon/containers/mastodon.js). If you try to do this:
```javascript
import kab from 'react-intl/locale-data/kab';
```
you'd catch error stating that it does not exists. The limitation is not in Mastodon but in [react-intl])https://github.com/yahoo/react-intl).

The library `react-intl` has limited support to different language. The source of it is [Unicode Common Locale Data Repository](http://cldr.unicode.org/) and it is far from complete. Less popular language (e.g. languages covered in ISO 639-2) were likely not included.

The principle in the change in mastodon.js is to have locale data supplied to `addLocaleData()`.
It is not necessary to use the data they provide. You can provide your own locale data as long as it goes along with their [Locale Data API](https://github.com/yahoo/react-intl/wiki/API#locale-data-apis).

tootsuite/mastodon#2845 includes an [example implementation](https://github.com/tootsuite/mastodon/blob/ca05bfaac7894285bf9ebbfeebe8c379b94eeb42/app/javascript/mastodon/locales/locale-data/oc.js) of such locale data. You can read the [README.md](https://github.com/tootsuite/mastodon/blob/ca05bfaac7894285bf9ebbfeebe8c379b94eeb42/app/javascript/mastodon/locales/locale-data/README.md) and start there.

You may also find how it is [imported](https://github.com/tootsuite/mastodon/blob/ca05bfaac7894285bf9ebbfeebe8c379b94eeb42/app/javascript/mastodon/containers/mastodon.js#L63) and [used](https://github.com/tootsuite/mastodon/blob/ca05bfaac7894285bf9ebbfeebe8c379b94eeb42/app/javascript/mastodon/containers/mastodon.js#L99) in `mastodon.js`.

**Comment by Artoria2e5** [comment]
@yookoala how does the ruby part work with custom locales' plural rules though?

**Comment by yookoala** [comment]
@Artoria2e5: You may read about RoR's i18n documentation for this:
http://guides.rubyonrails.org/i18n.html#pluralization

**Comment by Artoria2e5** [comment]
It doesn't seem to mention an interface for adding custom ones...

**Comment by belkacem77** [comment]
@yookoala 
Kab is available on Firefox for all plateforms. I'am the Kabyle L10N Driver for Mozilla :)  
Please see. www.mozilla.com/kab

I will see with my kab team for details

**Comment by yookoala** [comment]
I checked "Firefox > Preferences > Content > Languages". And I couldn't find a "`Kabyle [kab]`" option. I think that is how you'd set the [Accepted-Language](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language) request header and have the web servers auto-detect languages.

Could that be a missing piece in the Firefox translation?
Or it is just not available to other interface language version?

Not a prerequisites to contribute translation here. Just a friendly discussion on a situation I found. Glad to see people passionate about their language(s).

**Comment by yookoala** [comment]
> @Artoria2e5: It doesn't seem to mention an interface for adding custom ones...

Sorry. Misread your message. The documentation didn't talk about custom pluralization rules.

Did some extended reading. I found someone in stackoverflow talks about [customize pluralization rules in Rails 3.0.7](http://stackoverflow.com/questions/6166064/i18n-pluralization). It is not mentioned in neither the Rails Guide 3.2 or 5.1. I am not sure it still works the same way but it worth a try.

**Comment by dariusk** [comment]
@belkacem77 Can you re-open this issue in [the main Mastodon development repo](https://github.com/tootsuite/mastodon)? This isn't a documentation problem but rather a feature request for core Mastodon localization functionality.

Closing it here, but again, I encourage you to re-open this over there, where it's more likely to be seen by people who can do something about it!
