### ISSUE TITLE
Detecting if user already authorized an app during oauth flow

### ISSUE THREAD

**Issue by sull** [tootsuite/documentation#148]
What is the recommended procedure for detecting if user already has authorized an app via oauth and to avoid duplicate apps getting created?

**Comment by sull** [comment]
I saw some previous discussions on this and better understand why this is by design.

https://github.com/tootsuite/mastodon/issues/45
https://github.com/tootsuite/mastodon-api/issues/4

I wonder if we can come up with a more elegant approach or at least a way to group authorized apps in the UI (user only sees latest one?) so revoke one revokes all in the group with same name/attributes? 

Related.... An API endpoint for returning a users authorized apps would be helpful. Don't know if that would require authenticated endpoint (like instance API endpoints) but it maybe should be limited to the instance admin users for privacy concerns... So the endpoint might have a check for this.

**Comment by wxcafe** [comment]
is this still a thing?

**Comment by tateisu** [comment]
I have same issue.

if we have verify a client registration is still alive or not, we can reuse client information.
but currently my app can't verify the client registration is still alive or not.
then my app always re-register  client app information. 
It waste server's database rows.

**Comment by wxcafe** [comment]
I think this issue should be opened in tootsuite/mastodon instead of here. When it's implemented in the API then we can document it. Please open an issue there

**Comment by tateisu** [comment]
https://github.com/tootsuite/mastodon/issues/5104
