### ISSUE TITLE
Step-By-Step Upgrades

### ISSUE THREAD

**Issue by chiyancheung** [tootsuite/documentation#156]
I have several questions about upgrading to the newest version:

1. How do I find out what version I'm running right now?
2. How do I find out what's the latest stable version?
3. Is there a step-by-step guide on how to upgrade from my current version to the latest? 
4. I'm running Ubuntu... would the steps be different for different Linux distros?
5. If I'm several versions behind, do I need to upgrade to each incremental version, or can I upgrade directly  to the latest version?

Thanks!

**Comment by wxcafe** [comment]
1. You can look at the git commit, and at the git tag. While you're in the install directory, run `git describe --tag` and the first part is the closest tag that you're on with the second part being the number of commits since this tag on your version, and the third the id of the commit you're currently on.

2. You can look at https://github.com/tootsuite/mastodon/releases

3. There's some info in https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md, and more info on the releases page on the mastodon main repo

4. They could be, but they most likely aren't. The install steps would be pretty different if the other distro is not based on debian.

5. You can upgrade directly to the latest version.

I'm closing this issue. If your questions haven't been answered correctly feel free to open it again :)

**Comment by chiyancheung** [comment]
Regarding #3 (step-by-step guide), the production guide has the following commands regarding upgrading:

------------
cd ~mastodon/live/
git fetch
git checkout $(git tag | tail -n 1)
RAILS_ENV=production bundle exec rails db:migrate
yarn install --pure-lockfile
RAILS_ENV=production bundle exec rails assets:precompile
------------

Should I run these commands one at a time, in this order? I setup my current instance on Ubuntu, Docker, and nginx, by following this guide: https://github.com/ummjackson/mastodon-guide/blob/master/up-and-running.md

**Comment by wxcafe** [comment]
yeah, though do also read the release notes on https://github.com/tootsuite/mastodon/releases :)

**Comment by chiyancheung** [comment]
I'm stuck on the first step: cd ~mastodon/live/
It says "-bash: cd: live: No such file or directory"

I see the following In the ~/masdodon directory:

app       config.ru           docs               LICENSE       Rakefile       streaming
app.json  CONTRIBUTING.md     Gemfile            log           README.md      Vagrantfile
bin       db                  Gemfile.lock       package.json  scalingo.json  vendor
Capfile   docker-compose.yml  ISSUE_TEMPLATE.md  Procfile      spec           yarn.lock
config    Dockerfile          lib                public        storybook

**Comment by wxcafe** [comment]
Hey, sorry I wasn't there. That looks like you cloned the repo in ~mastodon/mastodon instead of ~mastodon/live, but it's not a big problem. I guess in 6 days you moved on tho, so please update if you still need help and I'll be happy to answer your question

**Comment by chiyancheung** [comment]
Hi,
Thanks for following up. I'm now stuck on this command:
----------------------------------------------------
mastodon@myinstance:~/mastodon$ RAILS_ENV=production bundle exec rails db:migrate

[!] There was an error parsing `Gemfile`: no implicit conversion of Symbol into Integer. Bundler cannot continue.

 #  from /home/mastodon/mastodon/Gemfile:4
 #  -------------------------------------------
 #  source 'https://rubygems.org'
 >  ruby '>= 2.3.0', '< 2.5.0'
 #
 #  -------------------------------------------
----------------------------------------------------

Please help!
Thanks.

**Comment by wxcafe** [comment]
do you have rbenv and rbenv-build installed, as specified in the Production Guide?

**Comment by chiyancheung** [comment]
Yes, I have confirmed that rbenv and rbenv-build are both installed, but I still get the same "There was an error parsing 'Gemfile'" error message when I run this command:

RAILS_ENV=production bundle exec rails db:migrate

**Comment by wxcafe** [comment]
try to `gem update bundler`

**Comment by chiyancheung** [comment]
OK, I ran gem update bundler. Now I get a different error message:

`mastodon@myinstance:~/mastodon$ RAILS_ENV=production bundle exec rails db:migrate`

bundler: command not found: rails
Install missing gem executables with `bundle install`

**Comment by wxcafe** [comment]
Do what it says, run `bundle install`...

Clément 'wxcafé' Hertling

**Comment by chiyancheung** [comment]
I executed 'bundle install', it gave me an error, telling me to execute 'gem install nio4r -v '2.0.0''. When I did that, I get the following error:

gem install nio4r -v '2.0.0'

---------------
Building native extensions.  This could take a while...
ERROR:  Error installing nio4r:
        ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/nio4r-2.0.0/ext/nio4r
/usr/bin/ruby2.3 -r ./siteconf20170517-78690-1v1sb2m.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/nio4r-2.0.0 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/nio4r-2.0.0/gem_make.out
---------------

Sorry for having some many issues... thanks for your continued support.

**Comment by wxcafe** [comment]
Have you installed the dependencies at the beginning of the production
guide? Your problem seems to come from the fact that you don't have the
headers for ruby, which means you need the package `ruby-dev` or
something like that.

**Comment by chiyancheung** [comment]
Thanks for the info... I installed ruby-dev, I also installed build-essential patch

Now it tells me to install openssl, so I ran this: 
sudo gem install openssl -v '2.0.3'

And got this error:

Building native extensions.  This could take a while...
ERROR:  Error installing openssl:
        ERROR: Failed to build gem native extension.

**Comment by wxcafe** [comment]
what does it tell you exactly when you say "install openssl"? Can't you `apt-get install openssl openssl-dev`?

**Comment by chiyancheung** [comment]
Here are some additional commands that I tried:

`$bundle install`
An error occurred while installing openssl (2.0.3), and Bundler cannot continue.
Make sure that `gem install openssl -v '2.0.3'` succeeds before bundling.

`$ sudo gem install openssl -v '2.0.3'`
Building native extensions.  This could take a while...
ERROR:  Error installing openssl:
        ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/openssl-2.0.3/ext/openssl
/usr/bin/ruby2.3 -r ./siteconf20170519-17425-1xmulg8.rb extconf.rb
checking for t_open() in -lnsl... no
checking for socket() in -lsocket... no
checking for openssl/ssl.h... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

`$ sudo apt-get install openssl openssl-dev`
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package openssl-dev

`$ sudo apt-get install openssl`
Reading package lists... Done
Building dependency tree
Reading state information... Done
openssl is already the newest version (1.0.2g-1ubuntu4.6).
The following packages were automatically installed and are no longer required:
  linux-headers-4.4.0-62 linux-headers-4.4.0-62-generic linux-headers-4.4.0-72
  linux-headers-4.4.0-72-generic linux-image-4.4.0-62-generic linux-image-4.4.0-72-generic
  linux-image-extra-4.4.0-62-generic linux-image-extra-4.4.0-72-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 43 not upgraded.

$ sudo apt-get install openssl=2.0.3
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Version '2.0.3' for 'openssl' was not found

**Comment by wxcafe** [comment]
sorry the package for debian isn't openssl-dev it's libssl-dev.

**Comment by chiyancheung** [comment]
Thanks. That resolved the openssl issue. 
Also, I had to execute `sudo apt-get install libpq-de` to resolve a separate issue with pg. Now I'm getting a connection timeout error. The database is on the same server. I'm not sure where the IP address 160.83.8.143 comes from.

'$ RAILS_ENV=production bundle exec rails db:migrate'

rails aborted!
PG::ConnectionBad: could not connect to server: Connection timed out
        Is the server running on host "db" (160.83.8.143) and accepting
        TCP/IP connections on port 5432?

**Comment by wxcafe** [comment]
you need to change the database host  in your .env.production file.
