### ISSUE TITLE
documentation error for posting reports through API

### ISSUE THREAD

**Issue by jeroensmeets** [tootsuite/documentation#173]
for reporting a user on endpoint `api/v1/reports` the documentation says

`status_ids: The IDs of statuses to report (can be an array)`

It seems the status_ids must be an array, otherwise a 404 is returned. So `(can be an array)` should be `(array)`.

**Comment by dariusk** [comment]
Have you tested this with a single ID? A lot of times an API will take either a string of a single ID or an array of IDs.

**Comment by jeroensmeets** [comment]
Yes, for a single integer, a 404 is returned. Have tested several different configurations.

**Comment by ornithocoder** [comment]
Yep. This endpoint takes an array and the array needs to be encoded as [described here](https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md#parameter-types) (as with empty square brackets).

**Comment by wxcafe** [comment]
is this still a problem?
