### ISSUE TITLE
Request: how to deploy two or more instances on a server

### ISSUE THREAD

**Issue by jeroenpraat** [tootsuite/documentation#174]
Can someone please explain how to run two or more instances on a server? For docker deployments and non-docker deployments.

**Comment by dariusk** [comment]
Hi! General questions about administration are probably best posed to the mastodon-admin mailing list. They're very helpful on there, I usually hear back pretty quickly about instance admin questions.

https://lists.ffdn.org/wws/subscribe/mastodon-admin
