### ISSUE TITLE
Step-By-Step Upgrade Guide

### ISSUE THREAD

**Issue by chiyancheung** [tootsuite/documentation#240]
I setup my current instance on Ubuntu, Docker, and nginx, by following this guide: https://github.com/ummjackson/mastodon-guide/blob/master/up-and-running.md

Can someone please write a step-by-step guide to upgrade my instance to the latest version?

Thanks!

**Comment by wxcafe** [comment]
hey @chiyancheung given the discussion we've had over on tootsuite/mastodon I think we can close this issue, what do you think?

**Comment by chiyancheung** [comment]
Yes, please close this issue. Thanks for all your help!
