### ISSUE TITLE
Development guide needs updating

### ISSUE THREAD

**Issue by aral** [tootsuite/documentation#248]
The [development guide](https://github.com/drasticactions/documentation/blob/master/Running-Mastodon/Development-guide.md) is out of date. Specifically, it doesn’t mention that you need to run a separate server for the webpack assets (images, CSS).

Before:

```
You can then run Mastodon with:

bundle exec rails server
```

We should add a note about starting the webpack dev server:

```
./bin/webpack-dev-server
```

And/or, as @nightpool was mentioning in web chat, the development guide should get developers ready with the foreman workflow.

**Comment by aral** [comment]
As per @Gargron, there’s a PR that updates the docs that’s awaiting completion: https://github.com/tootsuite/documentation/pull/244

**Comment by aral** [comment]
Also, we should specifically mention that sidekiq requires `redis-server` to be run before `foreman start`

**Comment by jumbosushi** [comment]
Just had this problem where I couldn't start the server since I wasn't running webpack-dev-server. Hope PR will be merged soon!

**Comment by Gargron** [comment]
Merged.
