### ISSUE TITLE
Please add my Android app to the list

### ISSUE THREAD

**Issue by FlorentAnders** [tootsuite/documentation#259]
Hello.

I have decided to build an open source and GPLv3 conforming Mastodon client for Android based on Tusky.

Google Play: http://play.google.com/store/apps/details?id=com.fa.imaged
GitHub: https://github.com/FlorentAnders/Panoramic

Please add it to the list:)

Greetings!

**Comment by wxcafe** [comment]
Can you please make a PR? We can then simply merge it and everyone's happy

**Comment by FlorentAnders** [comment]
Sure, I'll.
