### ISSUE TITLE
Consider using a documentation-specific license

### ISSUE THREAD

**Issue by tswast** [tootsuite/documentation#262]
The GFDL might make more sense for this repo: https://www.gnu.org/licenses/licenses.html#FDL

Or one of the Creative Commons licenses, like the one Wikipedia uses: https://en.wikipedia.org/wiki/Wikipedia:Text_of_Creative_Commons_Attribution-ShareAlike_3.0_Unported_License

The [A]GPL license wasn't intended to be used in non-software contexts: https://www.gnu.org/licenses/gpl-faq.html#GPLOtherThanSoftware

**Comment by wxcafe** [comment]
@Gargron why did you reopen this, and has this changed since jul 25? If so, what is the plan?

**Comment by wxcafe** [comment]
up @Gargron

**Comment by Gargron** [comment]
@wxcafe Hmm I didn't reopen it. I think the revert of that PR re-opened the issue automatically. I reverted because:

>Need agreement from contributors first.

Which is kind of a PITA
