### ISSUE TITLE
API documentation is incomplete re: notifications

### ISSUE THREAD

**Issue by Kimik0** [tootsuite/documentation#265]
The notifications/dismiss/**id** one is missing. It seems to have been added on 23 April, but also removed again?

There's also no mention of the possibility of filtering notifications by type. The web interface makes use of it, so it's clearly not meant to be hidden. It's most useful for automated API use to get mentions separately from other types, so please document it fully.

**Comment by ornithocoder** [comment]
The feature to dismiss a single notification is definitely there. See [here](https://github.com/tootsuite/mastodon/blob/b6f6152e263cdf12f61f9ae3d65c351a4dec7c61/spec/controllers/api/v1/notifications_controller_spec.rb#L26) and [here](https://github.com/tootsuite/mastodon/blob/05ac28f3e451c9239093f55a32e9f1eda770f8fa/app/controllers/api/v1/notifications_controller.rb#L34). What does the commit that removes it say?

Feel free to submit a pull requesting adding the endpoint back to the documentation. Additionally, you can include these links on the PR details, explaining why you're adding the endpoint to the documentation.

**Comment by Kimik0** [comment]
I can't figure out how it was removed actually. Looking at https://github.com/tootsuite/documentation/commits/master/Using-the-API/API.md it seems to have been added on 23 April because https://github.com/tootsuite/documentation/blob/b2e03c18f96c215a05d304935e390cb9c62055a4/Using-the-API/API.md#notifications lists it. And it was removed by the next commit apparently, because https://github.com/tootsuite/documentation/blob/05ec8112afb2a4a73a37d62773f9162f418fa77c/Using-the-API/API.md#notifications doesn't list it anymore. Yet it doesn't appear in the commit itself. Or maybe I'm not using GitHub right?

I don't know how to pull request. I'm asking about it here because I wanted to use the API. It turns out that's very hard if you're not a good programmer and the documentation doesn't include copious examples. I guess I'll have to look into using a command line interface that's higher level than curl ^_^;

**Comment by ornithocoder** [comment]
No problem. I'll create a pull request right now and mention you and this thread there.
