### ISSUE TITLE
Docs for /oauth/ routes

### ISSUE THREAD

**Issue by matteodem** [tootsuite/documentation#271]
Routes like `/oauth/token` and `/oauth/authorize` should be part of the API documentation: https://github.com/tootsuite/documentation/blob/master/Using-the-API/API.md

**Comment by Gargron** [comment]
They are documented in the Doorkeeper wiki, which is linked from <https://github.com/tootsuite/documentation/blob/master/Using-the-API/OAuth-details.md>

**Comment by matteodem** [comment]
Can we direct-link to the explanation for both of these routes? Seems pretty central to coding an app for mastodon.

**Comment by ramlmn** [comment]
@Gargron I think a tiny doc should be written for it, including a few notes like `/oauth/token/` doesn't work with the trailing slash (I've figured that out after struggling for a couple of days).

A tiny step by step process algorithm would help a lot.
