### ISSUE TITLE
Production-Guide:  git checkout $(git tag | tail -n 1) does not work for 1.4.1 

### ISSUE THREAD

**Issue by abochmann** [tootsuite/documentation#280]
In several places of the documentation, the command  _git checkout $(git tag | tail -n 1)_ is used to pull the latest version of the code.

Due to the sorting of _git tag_ output, this currently checks out v1.4rc6 instead of v1.4.1

**Comment by wxcafe** [comment]
I think RCs should probably have been named 1.4.0rcX instead of 1.4rcX, which would have made this problem moot. @Gargron let's do that for 1.5 pls? In the meantime I guess the only solution is to replace all `$(git tag | tail -n 1)` in the doc with `v1.4.1` :/

**Comment by abochmann** [comment]
Since most people will only want to check out the releases, excluding the rc versions a la `$(git tag | egrep -v rc | tail -n 1) `  might work as a stopgap, as long as that versioning scheme is being used. 
I have no idea how to do git versioning in a way that always keeps the newest release at the end of the `git tag` list.

**Comment by abochmann** [comment]
Seems this has already been fixed by using `git tag -l | sort -V` in the docs, so I'll close this issue.
