### ISSUE TITLE
specifications

### ISSUE THREAD

**Issue by benoitc** [tootsuite/documentation#308]
Is there any more details on how the protocols in mastodon  are implemented ? Other than the FAQ to allow server alternatives ?

**Comment by benoitc** [comment]
i found: https://github.com/tootsuite/documentation/blob/master/Extensions.md

but is this all what's needed? any restrictions on how the rfcs are implemented?

**Comment by Gargron** [comment]
You might need this page? https://github.com/tootsuite/documentation/blob/master/Specs-and-RFCs-used.md

>any restrictions on how the rfcs are implemented?

Standards compliant

**Comment by wxcafe** [comment]
Closing this
