### ISSUE TITLE
Production Guide: git checkout command doesn’t get latest tag

### ISSUE THREAD

**Issue by aral** [tootsuite/documentation#309]
The command stated in the Production Guide will not checkout the latest tag due to release candidate tags appearing lower in the list as returned by `git tag`:

`git checkout $(git tag | tail -n 1)`

Currently gets v1.4rc6 instead of v1.4.3.

There are two options as I see it to fixing this:

1. Rename the RC tags. (Might break things)
2. Change the instructions in the document (this will be a more manual process where the person has to find the latest version number and substitute it)

Or…

3. Something I haven’t thought of that’s a better solution :)

**Comment by Gargron** [comment]
Apparently `git tag -l --sort=version:refname` should return the right result

**Comment by aral** [comment]
I’m still getting the following from that:

`
…
v1.3.3
v1.4.1
v1.4.2
v1.4.3
v1.4rc1
v1.4rc2
v1.4rc3
v1.4rc4
v1.4rc5
v1.4rc6
`

**Comment by aral** [comment]
Here we go, this works:

`git tag -l | sort -V`
