### ISSUE TITLE
High-Level Changelog for the API

### ISSUE THREAD

**Issue by halcy** [tootsuite/documentation#311]
Right now, it's hard to tell which things were added to the API in which version at a glance.

I'd like to propose that the API documentation should, from now on forward, include a Changelog (that doesn't need to be more complicated than just "1.4.1: added X, Y and Z"). This would make it a LOT easier for me (and probably other library authors) to keep up with changes - right now, I have to comb through git history, and miss stuff often.

**Comment by Kimik0** [comment]
Yes please.

**Comment by wxcafe** [comment]
#236 duplicate?
