### ISSUE TITLE
List of Rake tasks

### ISSUE THREAD

**Issue by noraworld** [tootsuite/documentation#330]
I could not find the documentation of the list of Rake tasks. I think this documentation is helpful for us to confirm all Rake tasks clearly and quickly. The command to show the usage of each task (`bundle exec rails rake -T`) is helpful but we don't know the detailed information and the usage examples.

**Comment by dleevus** [comment]
This should help

https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Maintenance-Tasks.md

**Comment by noraworld** [comment]
@dleevus Yeah, of course. But not all Rake task is included in it. I think it is more helpful to confirm all tasks in this documentation.

I sent a pull request #331, so I wish this pull request is reviewed and merged.
