### ISSUE TITLE
What kind of machine would be recommended for running an instance?

### ISSUE THREAD

**Issue by WildYorkies** [tootsuite/documentation#36]
Can we get recommended machine specs for different numbers of users?

**Comment by wxcafe** [comment]
I'll start a page with my personal experience and send an email to the admin mailing list to ask them to help

**Comment by iamgreaser** [comment]
For a single-server setup, minimum 2GB of RAM unless you like to swap. This is assuming you don't add in extra workers - I don't know how much each worker costs in each department.

**Comment by wxcafe** [comment]
Two things : this is way too much, and this issue is about editing the documentation, not about answering the question in the comments

**Comment by WildYorkies** [comment]
@wxcafe Perhaps this should also be written assuming that the admin will be using Docker (if that makes a difference)

**Comment by wxcafe** [comment]
Yep it does. I'll make two sections, with and without docker.

Clément 'wxcafé' Hertling

**Comment by wxcafe** [comment]
done in 77469f4
