### ISSUE TITLE
New production guide leaves out section on upgrading

### ISSUE THREAD

**Issue by nightpool** [tootsuite/documentation#365]
"How to upgrade Mastodon" was a section in the old production guide, but is completely missing from the new version. This should probably be re-added.

https://github.com/tootsuite/documentation/blob/dd52795d7d1f5cd68b3cfb763321d3083db9b28b/Running-Mastodon/Production-guide.md#things-to-look-out-for-when-upgrading-mastodon

**Comment by nightpool** [comment]
https://mastodon.zombocloud.com/users/staticsafe/updates/4890

looks like @staticsafe is working on a new doc for this

**Comment by staticsafe** [comment]
opened pull request with my new updating guide:
https://github.com/tootsuite/documentation/pull/367

**Comment by nightpool** [comment]
closed by #367
