### ISSUE TITLE
Gem install bundler error

### ISSUE THREAD

**Issue by Colby-T** [tootsuite/documentation#371]
On a clean install of Ubuntu 16.04 server following instructions as provided in document:

attempt to run "gem install bundler"

Receiving error stating: The Program 'Gem' is currently not installed. To run 'gem' please ask your administrator to install the package 'ruby'

**Comment by awooga** [comment]
What document are you installing from exactly - i have built 1.5 mastodon recently and found online guidance had minor issues that could be easily overcome from competant linux expert - so can give guidance if needed. Happy to review installation document for Ubuntu 16.04 but struggling to find where that document exists on here ?

**Comment by Gargron** [comment]
@awooga https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md

**Comment by Colby-T** [comment]
I was able to get an install to work.
That particular issue was caused by the ruby environment not starting properly.
I was able to resolve that issue as it was a local issue with my hardware and was not with the process document.
This issue can be closed.
