### ISSUE TITLE
Typos in documentation

### ISSUE THREAD

**Issue by p2635** [tootsuite/documentation#382]
**FAQS**
Should it say 'posted' here instead of boosted?
https://github.com/tootsuite/documentation/blob/master/Using-Mastodon/FAQ.md#if-i-delete-a-post-does-it-get-deleted-everywhere

"If I delete a post, does it get deleted everywhere?

Deleting a post will delete it from the local timeline. However, if it has already been **boosted**, it may still be seen and may federate."

**Comment by p2635** [comment]
Another one in:
https://github.com/tootsuite/documentation/blob/master/Contributing-to-Mastodon/Translating.md#check-your-translations

Should say 'language' here:
To see if you lanuage is doing good, you may mix using the command tools, like this:

**Comment by m4sk1n** [comment]
@p2635, no, it's about Mastodon's feature – boosting toots, that's like reposting tweets. I'll make PR for the second one.

**Comment by wxcafe** [comment]
Closing since it's been fixed
