### ISSUE TITLE
No space on device

### ISSUE THREAD

**Issue by Elmit2015** [tootsuite/documentation#387]
I am 1.4.7 using docker. 

During my initial setup 1.2.3 I used these chrontab entries:

0 1 * * * /usr/local/bin/docker-compose run --rm web rake
mastodon:media:clear
0 2 * * * /usr/local/bin/docker-compose run --rm web rake
mastodon:push:refresh
0 3 * * * /usr/local/bin/docker-compose run --rm web rake
mastodon:feeds:clear

I think there is one entry missing to delete older entries. Can you tell
me which? Is the above still correct?

**Comment by Gargron** [comment]
https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/List-of-Rake-tasks.md#media-storage

**Comment by wxcafe** [comment]
Closing since question has been answered
