### ISSUE TITLE
git tag -l | sort -V | tail -n 1 display RC tags

### ISSUE THREAD

**Issue by Angristan** [tootsuite/documentation#390]
In the [Production Guide](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md):

```
# Checkout to the latest stable branch
git checkout $(git tag -l | sort -V | tail -n 1)
```

`git tag -l | sort -V | tail -n 1` will display the latest RC tag instead of the current stable release.

For example, 1.6.0 is out but the command shows `v1.6.0rc5`.

This is an issue as new instance admins using the guide will deploy RC tags.

**Comment by liptanbiswas** [comment]
#392
