### ISSUE TITLE
Deployment guides should include section on configuring logrotate to delete old server logs

### ISSUE THREAD

**Issue by sdukhovni** [tootsuite/documentation#393]
In mastodon's default terms of service, it says that the server operators "will make a good-faith effort to retain server logs containing the IP address of all requests to this server no more than 90 days". The deployment guides should help instance admins properly implement this policy.

**Comment by popoffka** [comment]
On Ubuntu 16.04, package nginx-common ships `/etc/logrotate.d/nginx` with the following contents:

```
/var/log/nginx/*.log {
	daily
	missingok
	rotate 14
	compress
	delaycompress
	notifempty
	create 0640 www-data adm
	sharedscripts
	prerotate
		if [ -d /etc/logrotate.d/httpd-prerotate ]; then \
			run-parts /etc/logrotate.d/httpd-prerotate; \
		fi \
	endscript
	postrotate
		invoke-rc.d nginx rotate >/dev/null 2>&1
	endscript
}
```

This should keep 14 days worth of logs, which is consistent with the default policy.

**Comment by sdukhovni** [comment]
Ok, never mind then :)
