### ISSUE TITLE
Update translation file list to contain app/views/*_mailer/*.erb

### ISSUE THREAD

**Issue by Artoria2e5** [tootsuite/documentation#405]
Mastodon's range of translatable e-mails have greatly expanded since the last update of the list of files to translate. Maybe we should find a way to list files that does not require us to mention each of the e-mail templates...

**Comment by wxcafe** [comment]
good point. Would you consider making a PR? :)

**Comment by Artoria2e5** [comment]
I still haven't figured out what to do with them yet. Stash everything under a `<details>` tag? Use an asterisk and just link people to the directory?

**Comment by wxcafe** [comment]
I'd say link people to the directory would be a good solution, yeah
