### ISSUE TITLE
Upgrade to 1.6.1 from source required additional dependency installs

### ISSUE THREAD

**Issue by aral** [tootsuite/documentation#410]
I had to install libidn11-dev (and installed libicu-dev, also, when I saw it listed in the readme) after getting an error on `bundle install` that idn could not be found. I couldn’t see any mention in the release notes for these additional dependencies. (If I missed it, please feel free to close this issue.)

**Comment by Gargron** [comment]
What version did you upgrade from? That dependency was added in 1.5.0: https://github.com/tootsuite/mastodon/releases/tag/v1.5.0

**Comment by aral** [comment]
That is a distinct possibility and it’s in the notes, so closing this. Thanks, Eugen :)
