### ISSUE TITLE
No documentation on suspend/silence

### ISSUE THREAD

**Issue by camellirite** [tootsuite/documentation#426]
I've been searching for what these words mean, since the admin of the instance I'm a member of has suspended a few instances, I'd like to know what that means but I couldn't find any information about it.

**Comment by wxcafe** [comment]
That's right, it's a problem, and I'm gonna work on it as soon as I find some time/spoons to do so

**Comment by coreyreichle** [comment]
Looks like this bug is resolved?  Running-Mastodon/Administration-guide.md covers silence v suspending domains.

**Comment by wxcafe** [comment]
looks like someone did that before I could then!
