### ISSUE TITLE
Document the types of attributes of the JSON responses in the API

### ISSUE THREAD

**Issue by Feufochmar** [tootsuite/documentation#440]
I recently got an error in one of my application due to a type change in the API following an update of the instance I use (Mastodon 1.x => 2.0). One of the attribute of a response I'm reading have its type changed from a JSON number to a JSON string (containing a number).
In languages with strong typing, the JSON libraries do not usually deserialize the same way JSON numbers and JSON strings (different data types are returned after the deserialization, and you cannot manipulate them the same way). Since there is no description of the types in the API documentation, it's hard to tell which type is returned for some attributes unless an API call is done, and the type of attribute is manually checked.

**Comment by nightpool** [comment]
This change specifically I believe we call out in the documentation,
because it was very far-reaching. Let me see if I can verify that when I'm
at my computer.....

**Comment by wxcafe** [comment]
I'm closing this, apparently the specific change was documented and it's been over a month
