### ISSUE TITLE
Does mastodon support realtime notification between client and server.

### ISSUE THREAD

**Issue by jackvt93** [tootsuite/documentation#457]
I'm writing an application in android and I have problem about scheduling to get notification from server. Question is does mastodon server has already supported pushing mechanism like [pusher.com](https://pusher.com/) for we can listen on that channel?

**Comment by nightpool** [comment]
https://github.com/tootsuite/documentation/blob/master/Using-the-API/Streaming-API.md

**Comment by nightpool** [comment]
(oops, didn't mean to close.)

**Comment by wxcafe** [comment]
up @jackvt93 is your question answered?
