### ISSUE TITLE
not getting a email confirmation 

### ISSUE THREAD

**Issue by Erectilereptiler** [tootsuite/documentation#465]
Hello, my friend is trying to make an account but isn't getting a email confirmation.

**Comment by HorizonShadow** [comment]
I also have this problem.

The error I'm getting is less than helpful. 

`sidekiq_1    | [ActiveJob] [ActionMailer::DeliveryJob] [35e553ee-6f20-438d-99d3-55fc817714f1] Error performing ActionMailer::DeliveryJob (Job ID: 35e553ee-6f20-438d-99d3-55fc817714f1) from Sidekiq(mailers) in 60038.01ms: EOFError (end of file reached):`

**Comment by HorizonShadow** [comment]
Ah, I solved mine. I'm using Fastmail, and I had to set the port to 587, even though the documentation said to use 465

**Comment by nightpool** [comment]
@Erectilereptiler is this for your server or for someone else's?

**Comment by wxcafe** [comment]
Since there's been no answer for a week for this kind of problem, I'm closing this.
