### ISSUE TITLE
Need documentation for cloudflare fronting of instance

### ISSUE THREAD

**Issue by coreyreichle** [tootsuite/documentation#467]
I would do a pull request, but I'm not sure which document would be best for this.  if someone could point which one would be best, I'll work the PR.

There are some finer points needing covering if you are cdn fronting a domain, and a sub is hosting the instance, and just for CDN; along with some different nginx config

**Comment by wxcafe** [comment]
You should probably just create a new document in Running-Mastodon named CDNs with a *Cloudflare* section and add things there :) thanks!

**Comment by coreyreichle** [comment]
Pull request awaiting review.
