### ISSUE TITLE
Letsencrypt auto renewal instructions do not work on centos 7

### ISSUE THREAD

**Issue by Laurelai** [tootsuite/documentation#478]
The commands put in the cron job 
"#!/usr/bin/env bash
letsencrypt renew
systemctl reload nginx"

Do not work as the script will fail to renew when nginx is running.

Should be 
#!/usr/bin/env bash
letsencrypt renew  --pre-hook "service nginx stop" --post-hook "service nginx start"

**Comment by coreyreichle** [comment]
This might be an upstream bug, as you should be able to renew with nginx running, and just affecting a reload after completion (To prevent downtime).

**Comment by Laurelai** [comment]
Regardless centos 7 users should be made aware that the given cron job will not function as it would on other distros within the documentation until its fixed.

**Comment by coreyreichle** [comment]
Pull request waiting approval.

**Comment by nightpool** [comment]
@Laurelai can you describe the bug for us? I think it's likely that this is actually a problem with the way you originally set up certbot.

did you originally register using the standalone or webroots configuration tools?

**Comment by Laurelai** [comment]
I dont remember.

**Comment by nightpool** [comment]
you can check the renewal configuration file at `/etc/letsencrypt/renewal/CERTNAME.`

**Comment by Laurelai** [comment]
Ah looks like it was standalone

**Comment by nightpool** [comment]
Okay, closing the issue then since the production guide specifically specifies that you should use webroot to avoid this issue. You can reconfigure LE to use webroot by re-running the command from the production guide.
