### ISSUE TITLE
Readme and FAQ: donation: mention Liberapay

### ISSUE THREAD

**Issue by tuxayo** [tootsuite/documentation#479]
The [Liberapay](https://liberapay.com/Mastodon/) funding campaign isn't mentioned:

https://github.com/tootsuite/mastodon/blob/master/README.md
https://github.com/tootsuite/documentation/blob/master/Using-Mastodon/FAQ.md#how-is-mastodon-funded

**Comment by tuxayo** [comment]
Optional demand: Favor Liberapay instead of Patreon.
Reasons to do so:
- Liberapay is libre/open source software.
- Liberapay is better for EUR donors.
- Liberapay is better for small amount donors.
  - https://blog.patreon.com/updating-patreons-fee-structure/
  - https://kav2k.github.io/patreon_letter/
  - https://www.patreon.com/posts/15763662
  - https://www.patreon.com/posts/greed-15771065
  - https://www.patreon.com/posts/update-on-that-15780175
  - https://www.patreon.com/posts/15758286

**Comment by nightpool** [comment]
Librepay doesn't support pledge rewards which is why we don't favor it.
Adding the links should be fine though.

**Comment by rainbowmultiverse** [comment]
#522 

My first time referencing a pull request. Let's see if this works...

**Comment by levlaz** [comment]
This issue should be closed, all of the details about Librepay are now in the docs and on the joinmastodon.org page.
