### ISSUE TITLE
Release notes incorrect upgrade instruction

### ISSUE THREAD

**Issue by wimvanderbauwhede** [tootsuite/documentation#486]
The "Upgrade notes" section of the v2.1.0 release notes
https://github.com/tootsuite/mastodon/releases/
has an incorrect instruction:

RAILS=production bundle exec  mastodon:maintenance:migrate_photo_preview_cards

should be

RAILS_ENV=production bundle exec rails mastodon:maintenance:migrate_photo_preview_cards

**Comment by Gargron** [comment]
Aki fixed it

**Comment by wimvanderbauwhede** [comment]
Thank you!
