### ISSUE TITLE
My Mastadon account was removed without breaking any rules

### ISSUE THREAD

**Issue by StreetTeamAC** [tootsuite/documentation#498]
My Mastadon account was removed by the "Community Moderator Noëlle" who's page is here: https://mastodon.social/@CM_noelle

This of course was not before being berated by 2 other members who are bigoted.

I've only been on Mastadon for less than 48 hours. So what are the guidelines for moderators who abuse their powers?

Where is the proper place to report these issues to?

**Comment by StreetTeamAC** [comment]
How this gets responded to determines the quality of Mastadon as a whole.

**Comment by nightpool** [comment]
please do not create duplicate issues after you've already been informed of them being off topic. I've answered your question in more detail here: https://github.com/tootsuite/mastodon/issues/6118
