### ISSUE TITLE
Authorisation email sending issue in docker

### ISSUE THREAD

**Issue by udnshah** [tootsuite/documentation#515]
Hello All,

I have recently deployed a mastodon server setup using official docker image and docker-compose file.

my server is up but i am facing issues in authorization mails sending.

i get below error

`member.metastudio.org-mastodon-sidekiq | 2018-01-08T14:26:12.502Z 10 TID-goehxr4xw ActionMailer::DeliveryJob JID-67e7e998b94269456302043a INFO: fail: 0.343 sec
member.metastudio.org-mastodon-sidekiq | 2018-01-08T14:26:12.503Z 10 TID-goehxr4xw WARN: {"context":"Job raised exception","job":{"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"ActionMailer::DeliveryJob","queue":"mailers","args":[{"job_class":"ActionMailer::DeliveryJob","job_id":"950d49b1-c447-4653-9294-527d6a23b5e5","provider_job_id":null,"queue_name":"mailers","priority":null,"arguments":["UserMailer","confirmation_instructions","deliver_now",{"_aj_globalid":"gid://mastodon/User/1"},"7GtS9C9-g_HV2GsVfH_j",{"_aj_symbol_keys":[]}],"executions":0,"locale":"en"}],"retry":true,"jid":"67e7e998b94269456302043a","created_at":1515421393.2768104,"enqueued_at":1515421572.1588602,"error_message":"SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: wrong version number","error_class":"OpenSSL::SSL::SSLError","failed_at":1515421394.990498,"retry_count":2,"retried_at":1515421500.860259},"jobstr":"{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"ActionMailer::DeliveryJob\",\"queue\":\"mailers\",\"args\":[{\"job_class\":\"ActionMailer::DeliveryJob\",\"job_id\":\"950d49b1-c447-4653-9294-527d6a23b5e5\",\"provider_job_id\":null,\"queue_name\":\"mailers\",\"priority\":null,\"arguments\":[\"UserMailer\",\"confirmation_instructions\",\"deliver_now\",{\"_aj_globalid\":\"gid://mastodon/User/1\"},\"7GtS9C9-g_HV2GsVfH_j\",{\"_aj_symbol_keys\":[]}],\"executions\":0,\"locale\":\"en\"}],\"retry\":true,\"jid\":\"67e7e998b94269456302043a\",\"created_at\":1515421393.2768104,\"enqueued_at\":1515421572.1588602,\"error_message\":\"SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: wrong version number\",\"error_class\":\"OpenSSL::SSL::SSLError\",\"failed_at\":1515421394.990498,\"retry_count\":2,\"retried_at\":1515421500.860259}"}
member.metastudio.org-mastodon-sidekiq | 2018-01-08T14:26:12.503Z 10 TID-goehxr4xw WARN: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: wrong version number
`

This is related to openssl

please recommend me a solution

Also can any one help me in activating user from command-line?

Thank you

**Comment by wxcafe** [comment]
it looks like your email provider is using SSLv3, which is deprecated and we don't support anymore. You should probably change email providers.

**Comment by luchoster** [comment]
I have a different issue, but same question..

`Any way to activate a user from the command-line'? or maybe manually thru the DB?

**Comment by wxcafe** [comment]
you can activate a user through the command line, yes : https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/List-of-Rake-tasks.md#administrative

**Comment by nightpool** [comment]
You can also activate a user from the admin interface, FYI.

**Comment by luchoster** [comment]
Thanks @wxcafe 

@nightpool thanks, the problem is that my instance is not sending emails ... yet lol I need to find out what the issue with the emails is first.
