### ISSUE TITLE
An interface for reading documentation

### ISSUE THREAD

**Issue by nclm** [tootsuite/documentation#52]
This is a direct continuation of tootsuite/mastodon/issues/1247 on the main repo. The documentation as it is regardless of its content is not easy to browse and read because a Github repo isn’t made for this. We need to set-up a URL with an interface that access the folders and files here and display them in a pretty and navigable way. That’s the address we’ll share with people needing the user’s manual, possibly even having a link in the Mastodon interface itself.

Tools and services mentioned in the other thread:
* GitBook: http://gitbook.com
* Read the Docs:  https://readthedocs.org
* MkDocks: http://mkdocs.org
* PeachDocs: https://peachdocs.org

**Comment by bmann** [comment]
I'm spending some time experimenting with the tools listed.

Read the Docs needs a bunch of python and didn't work out of the box.

Gitbook needs some fiddling, but at least showed up after an initial Github sync https://bmann.gitbooks.io/mastodon-docs/content/

MkDocs and Peach mean hosting separately.

I will see where I get to with Gitbook.

**Comment by bmann** [comment]
OK, once I copy-pasted the outline from README to SUMMARY.md which Gitbook needs, it pretty much "just works".

See https://bmann.gitbooks.io/mastodon-docs/content/ -- it works!

I can clean up my fiddling and make the pull request to this repo to add SUMMARY.md, and then "someone" should own the Gitbook account. Let me know how I can help.

**Comment by nclm** [comment]
Great!

The ideal way would be that someone who is part of the Tootsuite organisation on Github create a Mastodon organisation on Gitbook and link the two. So we well have a nice https://mastodon.gitbooks.io/documentation URL and be able to have several people being part of the organisation on Gitbook to tweak the presentation, etc.

**Comment by wxcafe** [comment]
@Gargron maybe have something either on gitbooks or whatever? this should be easy and it would improve the docs situation a lot.
