### ISSUE TITLE
Error 403 trying follow new user

### ISSUE THREAD

**Issue by ghost** [tootsuite/documentation#521]
Hello,
I'm on mastodon.xyz and when I try to follow a new user from mamot.fr I have a 403 error.
Could you tell me why and how can I do to be able to follow this user ?
Thanks a lot

**Comment by adrien-s** [comment]
Hi ! I had the same error on lou.lt and my own instance (the first runs on v2.1.0 and mine is on v2.3.3), from two different accounts, (one on mastodon.xyz, and another on eunivers.social).

From what I saw on my instance the only information is that on puma's log i only see a line with «  method=POST path=/api/v1/accounts/<account id>/follow format=html controller=Api::V1::AccountsController action=follow status=403 » when I try to follow, which was a private account that I did follow in the past (the follow disappeared somehow).

Weirder again: I tried the @handle@instance in the searchbox again, and re-re-tried the follow a few minutes later… And it worked.
