### ISSUE TITLE
SSL/TLS Configuration: Detailed Guide?

### ISSUE THREAD

**Issue by Hobbit-Habit** [tootsuite/documentation#523]
Hi,

The Production Guide leaves a lot for the user to work out for himself as regards the configuration of SSL/TLS and certificates. Is there a more detailed description of the steps to configure the "example.com.conf" file? I'm just spending hours on Google searching for answers.

**Comment by nightpool** [comment]
https://mozilla.github.io/server-side-tls/ssl-config-generator/

**Comment by Hobbit-Habit** [comment]
Some more information (I've substituted "example.com" for my domain in the following):

1. http://example.com in a browser gives the nginx welcome page.
2. https://example.com gives page not found.
3. The SSL checker at https://www.sslshopper.com/ssl-checker.html says that no certificate was found at example.com.
4; The Mozilla template section of /etc/nginx/sites-available/example.com.conf is as follows:

    # certs sent to the client in SERVER HELLO are concatenated in ssl_certificate
#    ssl_certificate /path/to/signed_cert_plus_intermediates;
    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;
#    ssl_certificate_key /path/to/private_key;
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_session_tickets off;

    # Diffie-Hellman parameter for DHE ciphersuites, recommended 2048 bits
#    ssl_dhparam /path/to/dhparam.pem;
    ssl_dhparam /etc/ssl/certs/dhparam.pem;
    # intermediate configuration. tweak to your needs.
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-$    ssl_prefer_server_ciphers on;

    # HSTS (ngx_http_headers_module is required) (15768000 seconds = 6 months)
    add_header Strict-Transport-Security max-age=15768000;

    # OCSP Stapling ---
    # fetch OCSP records from URL in ssl_certificate and cache them
    ssl_stapling on;
    ssl_stapling_verify on;

    ## verify chain of trust of OCSP response using Root CA and Intermediate certs
#    ssl_trusted_certificate /path/to/root_CA_cert_plus_intermediates;
    ssl_trusted_certificate /etc/letsencrypt/live/example.com/chain.pem;
    resolver <IP DNS resolver>;

**Comment by ITwrx** [comment]
@Hobbit-Habit i don't know if you're still interested in this, but the fact that the welcome page is rendered over http but not via https means you're not serving the server block in question over https. you will need to change the port to 443 instead of 80 via the "listen" directive. like `listen      192.168.1.1:443 ssl;` but with your server's public ip address.
