### ISSUE TITLE
Need updating Docker-Guide

### ISSUE THREAD

**Issue by 84b9cb** [tootsuite/documentation#532]
LOCAL_HTTPS is no longer supported in production [#6061](https://github.com/tootsuite/mastodon/pull/6061) but Docker-Guide says
> You will need to fill in, at least: LOCAL_DOMAIN, LOCAL_HTTPS, and the SMTP_* settings.

> Then you may login to your new Mastodon instance by browsing to http://localhost:3000/

Would you mind updating the document?

**Comment by wxcafe** [comment]
@dariusk or someone who works with docker?

**Comment by Gargron** [comment]
Can confirm LOCAL_HTTPS is no longer an option. It's always "true".

**Comment by vaartis** [comment]
I'll try to update docker documentation up to the actual state, since i have been working with mastodon in docker for some time, @Gargron is that OK?
