### ISSUE TITLE
Issue in "Production" Guide - could not enable System D services with Wildcard

### ISSUE THREAD

**Issue by ryanfmurphy** [tootsuite/documentation#542]
Hello!  Just a caveat about an issue I had, that you may wish to update your doc to reflect.

While following the [Production Guide](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md) it told me to enable all 3 Mastodon services with a wildcard command:

    systemctl start mastodon-*.service

But checking the status, these 3 services did not start with that command.  I had to enable them 1 by 1:

    systemctl start mastodon-web.service
    systemctl start mastodon-sidekiq.service
    systemctl start mastodon-streaming.service

I am running Debian GNU/Linux 9.

Thanks for the excellent software!

**Comment by joshuatj** [comment]
I have the same issue. The wildcard just never worked for me.

**Comment by nightpool** [comment]
What version of systemctl are you using?

**Comment by tigre-bleu** [comment]
Same for me, wildcards are not working with systemd 232 (Debian stretch)

```
# systemctl --version
systemd 232
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
```

**Comment by benharri** [comment]
That means the wildcard is getting picked up by your shell. Try quoting it or escaping the `*`:
`'mastodon-*'`
`mastodon-\*`
