### ISSUE TITLE
Invalid symlinks break docker-compose build

### ISSUE THREAD

**Issue by ineffyble** [tootsuite/documentation#547]
Following the Docker Guide, I'm unable to run `docker-compose build` to build my own copies of the Masto images, because it errors out on files like public/500.html.

This is because they're symlinked to public/assets, which doesn't exist (yet).

Docs might need to be updated to account for this.

**Comment by moritzheiber** [comment]
As discussed, this is probably because of docker/compose#5686 and docker/docker-py#1841. The current recommended workaround is to downgrade to 1.18.0.
