### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by grafiktr** [tootsuite/documentation#552]
Hello, I make a living by translating articles, lectures and some other documents and I would like to help you by translating your project to Turkish. If you would like to work with me, could you please give me a permission for translation? Thank you in advanced.

**Comment by wxcafe** [comment]
Hi! If you want to translate the documentation in turkish, we'd really appreciate it! We're an open-source and free project though, so we can't pay anything for it. If you want to do a translation, you don't need any permissions, just make your changes and submit them as a pull request. Thanks for your interest!

**Comment by grafiktr** [comment]
@wxcafe okay, i got it. would you like to have the translations in /i18n/TR_tr/ file?

**Comment by wxcafe** [comment]
well, for now the translations have been written as `Original_File_name_LANG` (see https://github.com/tootsuite/documentation/tree/master/Using-Mastodon for example) so following that scheme would be good imo :) thank you!

**Comment by nightpool** [comment]
If you want to contribute Turkish documentation for mastodon, you may also wish to check out the Turkish localization file for the main project (https://github.com/tootsuite/mastodon/blob/master/config/locales/tr.yml or on weblate, https://weblate.joinmastodon.org/projects/mastodon/backend/tr/), for guidance on terminology, etc.

**Comment by grafiktr** [comment]
I can not continue the translations unless you marge them @wxcafe
