### ISSUE TITLE
Standalone Installation Guide Produces Errors

### ISSUE THREAD

**Issue by outragedhuman** [tootsuite/documentation#557]
Link to doc: https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md

Running on Ubuntu 16.04 like the guide states, and following the instructions to the letter is producing a couple of of issue which prevent completion of the guide and getting to the "fun stuff".   :)

This suggestion should probably be added to the guide to avoid errors when enabling rbenv:

https://github.com/rbenv/ruby-build/issues/156#issuecomment-54922357

Output similar to this issue when running bundle install, as described after trying `RAILS_ENV=production bundle exec rake secret`:

https://github.com/tootsuite/mastodon/issues/2804

Is displayed on 16.04 even though gcc versioning does not match up with issue 2804. Here's output of the `rake secret`:

```
$ RAILS_ENV=production bundle exec rake secret
Could not find cld3-3.2.2 in any of the sources
Run `bundle install` to install missing gems.
```

And the output of the `bundle install`:

[bundle install output.txt](https://github.com/tootsuite/documentation/files/1787491/bundle.install.output.txt)

And curiously (I don't claim to be a RoR guy, so maybe this isn't a huge deal) the command `gem install cld3 -v '3.2.2'` works fine, but yet the rake secret command still fails. 

Output of `dpkg --list | grep compiler`:

```
ii  g++                                 4:5.3.1-1ubuntu1                           amd64        GNU C++ compiler
ii  g++-5                               5.4.0-6ubuntu1~16.04.9                     amd64        GNU C++ compiler
ii  gcc                                 4:5.3.1-1ubuntu1                           amd64        GNU C compiler
ii  gcc-5                               5.4.0-6ubuntu1~16.04.9                     amd64        GNU C compiler
ii  libllvm5.0:amd64                    1:5.0-3~16.04.1                            amd64        Modular compiler and toolchain technologies, runtime library
ii  libprotoc9v5:amd64                  2.6.1-1.3                                  amd64        protocol buffers compiler library
ii  protobuf-compiler                   2.6.1-1.3                                  amd64        compiler for protocol buffer definition files
```

If someone could help me out with the rake secret problem I could post any additional issues I encounter while completing the guide. Aside from this, the docs are great, IMO!

**Comment by brograhamer** [comment]
+1

**Comment by Digasi** [comment]
I also struggled at the step where bundle install would not complete at the cld 3.2.2 install piece.
I found some random work around, (I believe i installed it manually, on it's own..or something.) Now it sees it as installed, but my home page displays all text with no graphics. So I'm sure I probably just messed it all up. ;) I will probably scrap the directory and database and start over...but there was definitely something a miss in that section of the walk-through or build pieces. (I suspect a build piece..The walk-through is a life saver...and really well done.) Just my 2 cents. :)

**Comment by outragedhuman** [comment]
Unfortunately I just gave up. I wanted to bring a community that was open sourced to light, but I guess the FOSS architecture for support just isn't quite there yet. It's sad, but it is what it is.

**Comment by michielbuddingh** [comment]
I've been able to work around this; the main issue seems to be that cld3 required gcc 6 to compile, but stock Ubuntu 16.04 only supplies gcc 5, and gcc 6 is available as a package only through ppa.

I've used this (https://launchpad.net/~jonathonf/+archive/ubuntu/gcc) ppa succesfully, and I hope I'll be able to find time later today to create a pull request for the documentation.
