### ISSUE TITLE
"Maintaining Mastodon" is sparse

### ISSUE THREAD

**Issue by digitalscofflaw** [tootsuite/documentation#573]
In light of the demise of mastodon.rocks due to lack of backup, I decided to check out the guides for preventing this situation. There's only one document in there, and it doesn't cover testing or restoring from backups.

Mastodon would be improved if someone with experience maintaining systems in general (and especially Mastodon) expanded it.

- Backup up
- Securing the backup (maybe go into off-site vs. local, encryption, access)
- Testing the backup (don't do it live!)
- Restoring from backup

**Comment by albjeremias** [comment]
A possible approach could be something like: https://github.com/libresh/backups

**Comment by wxcafe** [comment]
I'd say a guide to backups are out of scope of this guide. There are countless methods of doing backups, countless software to do them, and countless advice as to how often to do them, where to store them, how to test them, ...

I'd agree adding a how to on what to backup could be useful, but I'm pretty sure that's already covered in the guide.

**Comment by albjeremias** [comment]
aaah, already exists: https://github.com/tootsuite/documentation/blob/master/Maintaining-Mastodon/Backups-Guide.md
