### ISSUE TITLE
[very minor] Transfer repository

### ISSUE THREAD

**Issue by nightpool** [tootsuite/documentation#58]
Right now the repository looks like this:

![image](https://cloud.githubusercontent.com/assets/233815/25067270/25a9f8ee-220c-11e7-8c23-87bcba24b079.png)

it would be great if we could either have Github remove that (I hear they do it if you ask them), or have @dereckson transfer the repository to this account, so that you have the "original" copy and it doesn't show that message

**Comment by wxcafe** [comment]
yeah I asked @Gargron to ask github to do this earlier on the discord but I should probably assign him here

**Comment by Gargron** [comment]
Thanks to the kind team at GitHub, done! <3
