### ISSUE TITLE
Inaccuracies in docker mastodon guide

### ISSUE THREAD

**Issue by neunenak** [tootsuite/documentation#591]
I'm new to Mastodon and trying to follow along with https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Docker-Guide.md

Unfortunately, it seems like some of this documentation is incorrect (possibly out of date?) and I've been having trouble getting a working mastodon instance running by following it.

Some of the inconsistencies I've noticed are:
-nothing in that documentation mentions that the .env.production file needs to exist before `docker-compose build` will even run. I ended up renaming the default .env.production.sample file to .env.production to make the image happy, but I'm not sure why the build step is even checking for this
-if I'm using a prebuilt image from docker Hub rather than compiling from source, does `docker-compose build` even do anything? it seems like it doesn't
-when I run `docker-compose run --rm web rake mastodon:setup`, it's not clear to me how the .env.production file that this says it saves relates to the .env.production file that exists outside of docker, in the top-level directory of the cloned repo. When I actually run `docker-compose up` later, which .env.production will it look for?
-finally, it's not clear from the documentation what steps in the Production guide (https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md) are and are not necessary if running mastodon from docker

**Comment by SabreCat** [comment]
+1. I've run into all of the above confusions myself trying to work from the docker-compose guide.

In addition, you'll run into
https://github.com/tootsuite/mastodon/issues/6883
and
https://github.com/tootsuite/mastodon/issues/6911

if you follow the directions as written.

**Comment by nightpool** [comment]
@wxcafe i dont use docker

**Comment by neunenak** [comment]
Who is someone who deploys mastodon with docker? I'd like to deploy it this way myself and I'd like to help out with improving the documentation for it if I can.

**Comment by neunenak** [comment]
Another issue that I'm running into, when running `docker-compose run --rm web rake mastodon:setup`, is inconsistent behavior when running the `Prepare the database now? Yes
Running `RAILS_ENV=production rails db:setup` ...` step. The first time I ran it on my current machine, the contaainer exited with no error message after a few minutes. The next time I ran it, it reported `database postgres already exists
Killed`
. That said, I was able to get it running on another machine, so I don't know what's going on here.

**Comment by SabreCat** [comment]
@neunenak I just finished bringing up my own instance using docker-compose the other day, and ran into the same thing. It throws a warning that it'll delete any extant database if you choose to re-initialize, but it seems the script can't actually do that.

**Comment by SaiGonSeamus** [comment]
We're still running into these problems as well with v2.3.3 on prebuilt images doing a manual `chown -R 991:991 public`

```
Running `RAILS_ENV=production rails assets:precompile` ...

I, [2018-04-18T05:06:25.049295 #17]  INFO -- : Writing /mastodon/public/assets/doorkeeper/admin/application-50d68ad91b15067c63771e4811d971d7a56406c472a878021d1fb95d066efd8d.css
I, [2018-04-18T05:06:25.050087 #17]  INFO -- : Writing /mastodon/public/assets/doorkeeper/admin/application-50d68ad91b15067c63771e4811d971d7a56406c472a878021d1fb95d066efd8d.css.gz
I, [2018-04-18T05:06:25.059758 #17]  INFO -- : Writing /mastodon/public/assets/doorkeeper/application-29873392fba1f6a4fd5359214f854d900e24920096164f6e5343dbc0de69df0d.css
I, [2018-04-18T05:06:25.060004 #17]  INFO -- : Writing /mastodon/public/assets/doorkeeper/application-29873392fba1f6a4fd5359214f854d900e24920096164f6e5343dbc0de69df0d.css.gz
I, [2018-04-18T05:06:25.273337 #17]  INFO -- : Writing /mastodon/public/assets/pghero/application-3807e140de3bf52364d575c9c1cba1ed730999b53e2781da4bf8bb15b01791bf.js
I, [2018-04-18T05:06:25.273523 #17]  INFO -- : Writing /mastodon/public/assets/pghero/application-3807e140de3bf52364d575c9c1cba1ed730999b53e2781da4bf8bb15b01791bf.js.gz
I, [2018-04-18T05:06:25.280755 #17]  INFO -- : Writing /mastodon/public/assets/pghero/application-c2618b70600dfedb0f3ba1f916d97a2f93a3f265aba10356abb763bd663d0cbd.css
I, [2018-04-18T05:06:25.280938 #17]  INFO -- : Writing /mastodon/public/assets/pghero/application-c2618b70600dfedb0f3ba1f916d97a2f93a3f265aba10356abb763bd663d0cbd.css.gz
rails aborted!
Errno::EACCES: Permission denied @ dir_s_mkdir - /mastodon/public/assets/doorkeeper
/mastodon/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/asset.rb:163:in `write_to'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:209:in `block (2 levels) in compile'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/ivar.rb:170:in `safe_execute'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/future.rb:52:in `block in execute'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)

That failed! Maybe you need swap space?

All done! You can now power on the Mastodon server 🐘
```
We are using a bought cert rather than Let's encrypt.

Browser shows a 502 Bad Gateway and the error logs are giving this. 

`streaming_1  | ERR! Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379 `

Are the Mastodon systemd Service Files part of the deployment guide required for a docker install? it isn't clear.

**Comment by SabreCat** [comment]
@SaiGonSeamus That looks like https://github.com/tootsuite/mastodon/issues/6911 ? Try the `chown` command from step 5 of "building your own image" then rerunning the script.
