### ISSUE TITLE
Question about Silenced users?

### ISSUE THREAD

**Issue by ThisIsMissEm** [tootsuite/documentation#595]
I'm currently trying to understand what happens we silence a user with regards to Federation? Mainly, does a user silenced on our instance still reach the federated timeline on other instances?

I know we can silence on our instance and hide that user from anyone who's not following them on our instance, but does silencing them also hide them from anyone on other instances who are not following them?

If we have a user who's posting way too frequently, what can we do to not overload other instances?

**Comment by ThisIsMissEm** [comment]
Okay, but if I silence a user on my instance, does that prevent other instances from receiving their content in any way? Basically, we don't want to proliferate spam when we silence a user for posting way too much of the same content.

**Comment by Gargron** [comment]
No, silencing does not affect federation in any way, so it doesn't solve the spam problem on *other* servers.

**Comment by ThisIsMissEm** [comment]
Then I wonder: What tools do we have to deal with spam coming from our server other than performing a full suspension?

**Comment by ThisIsMissEm** [comment]
@steckerhalter because suspend permanently deletes everything immediately.
