### ISSUE TITLE
List of apps: missing apps, info and editabillity

### ISSUE THREAD

**Issue by DerKarlos** [tootsuite/documentation#605]
I like the **List of apps** but I miss apps
https://itunes.apple.com/de/app/stella-for-mastodon-twitter/id921372048?mt=8
https://itunes.apple.com/us/app/tootle-for-mastodon/id1236013466?mt=8
may be more.

And I miss more details like: sends Push notification

We could move this list to the Mastodon-Wiki do enable dynamic actualisation.
May be the whole documentation could be Wiki pages.

**Comment by IzzySoft** [comment]
While being on it: The OpenSource Android client 11t is also available [at IzzyOnDroid](https://android.izzysoft.de/repo/apk/com.jeroensmeets.mastodon).

And agreed to the Wiki proposal, we then could edit it ourselves and not put the work on you.
