### ISSUE TITLE
Small update to app list

### ISSUE THREAD

**Issue by IzzySoft** [tootsuite/documentation#628]
Don't want to fork,clone etc. just for this minor thing – so just a short update to your [list of Mastodon apps](https://github.com/tootsuite/documentation/blob/master/Using-Mastodon/Apps.md):

* 11t: also [at IzzyOnDroid](http://apt.izzysoft.de/fdroid/index/apk/com.jeroensmeets.mastodon) (RFP for F-Droid pending)
* [Toot](http://apt.izzysoft.de/fdroid/index/apk/xyz.gsora.toot) (though it seems no longer maintained)
* [Cloudier](https://github.com/beta/cloudier) is now integrating Mastodon
* [Twitlatte](https://github.com/moko256/twitlatte) is [at Playstore](https://play.google.com/store/apps/details?id=com.github.moko256.twitlatte) and <strike>on its way into</strike> [at F-Droid](https://f-droid.org/packages/com.github.moko256.twitlatte/)

**Comment by yannicka** [comment]
I would add [Tootle](https://github.com/bleakgrey/tootle) (a desktop client) and [Brutaldon](https://github.com/jfmcbrayer/brutaldon) (an alternative web client).
