### ISSUE TITLE
A guide for setting up lets encrypt?

### ISSUE THREAD

**Issue by songproducer** [tootsuite/documentation#63]
Hello,

Sorry I'm so noob at nginx. I'm following the guide [here](https://certbot.eff.org/#ubuntuxenial-nginx) and stuck at this question:

```
Select the webroot for monero.fun:
-------------------------------------------------------------------------------
1: Enter a new webroot
-------------------------------------------------------------------------------
Press 1 [enter] to confirm the selection (press 'c' to cancel): 1
Input the webroot for monero.fun: (Enter 'c' to cancel):

```

**Comment by wxcafe** [comment]
Sorry but I think this is out of scope for this documentation repo. This repo is only about mastodon itself. You should look at setting up let's encrypt before trying to install mastodon.
