### ISSUE TITLE
GET /api/v1/suggestions is undocumented

### ISSUE THREAD

**Issue by garbados** [tootsuite/documentation#645]
Added in https://github.com/tootsuite/mastodon/pull/7918, the follow recommendation API endpoint is not documented in this repository, though it has been included in a pre-release.

What does it do? How does it work? What is the math involved?

**Comment by nevillepark** [comment]
From [here](https://github.com/tootsuite/mastodon/pull/7918/commits/fc0c20f2b1a84bf0563d30797238ed8fc4cee354):

> ## Track interactions with people you don't follow
> 
> Replying to, favouriting and reblogging someone you're not following
> will make them show up in follow recommendations. The interactions
> have different weights:
> 
> - Replying is 1
> - Favouriting is 10 (decidedly positive interaction, but private)
> - Reblogging is 20
> 
> Following them, muting or blocking will remove them from the list,
> obviously.

**Comment by Gargron** [comment]
It has not been included in public releases (*especially* not plural), its first appearance is in 2.4.3rc1 (release candidate, "pre-release") which came out today.

The PR from the changelog includes both the API documentation and explanation of the math: https://github.com/tootsuite/mastodon/pull/7918

**Comment by garbados** [comment]
Updated the initial comment to reflect that it is included in a pre-release. Thanks for the clarification.

However, I don't find the API documentation in the PR sufficient. For example:

> What interactions? If you engage with a person you're not following, it bumps their score on your hidden list. Between replies, favourites and reblogs, the weight of the score bump is different. The idea is that you may have lots of positive interactions with a person, but forget to follow them.

The bump score is different. How? What is the math, rather than "the idea"?

**Comment by garbados** [comment]
The documentation included in the commit message is good and I believe it makes sense to include that information in the API documentation.

**Comment by Gargron** [comment]
The numbers are arbitrary, replying is the baseline, favouriting is more indicative than replying, and boosting is even more indicative than favouriting. 1-10-20.

**Comment by rinsuki** [comment]
I think this issue is closable in https://github.com/tootsuite/documentation/pull/646
