### ISSUE TITLE
[Feature Request] Documentation about upgrading needs to be added

### ISSUE THREAD

**Issue by WNYmathGuy** [tootsuite/documentation#651]
I successfully followed this guide to installing my Mastodon Instance back in April 2018:
[https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md) 

Just yesterday I wanted to upgrade and couldn't find any recipe for it. I found this guide but it was not a successful path for me ...
[https://anystack.xyz/how-to-install-mastodon-ubuntu/](https://anystack.xyz/how-to-install-mastodon-ubuntu/) 
... as you can see from this screen shot:
![screenshot from 2018-07-19 13-15-04](https://user-images.githubusercontent.com/28640985/42959198-e860420e-8b55-11e8-99fd-d076167b1ae0.png)

I believed the only major error I had was ...
```
~/live$ RAILS_ENV=production bundle exec rails db:migrate
Migrating to RevertIndexChangeOnStatusesForApiV1AccountsAccountIdStatuses (20180514140000)
== 20180514140000 RevertIndexChangeOnStatusesForApiV1AccountsAccountIdStatuses: migrating 
-- index_exists?(:statuses, {:name=>"index_statuses_20180106"})
   -> 0.0068s
-- add_index(:statuses, [:account_id, :id, :visibility, :updated_at], {:order=>{:id=>:desc}, :algorithm=>:concurrently, :name=>:index_statuses_20180106})
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

Index name 'index_statuses_20180106' on table 'statuses' already exists
```

... so, thinking I was clever, I deleted the index `index_statuses_20180106` from my existing Mastodon PgSQL database and that command ran successfully on the second attempt, but I still have a non-working Mastodon instance. It's no great loss yet because I only have one user that isn't me and only a couple statuses. 

Now I'm stuck where it doesn't work and I don't know how to roll back or go forward or fix it. Any reliable upgrade guide would have prevented this.

**Comment by nightpool** [comment]
we have an upgrading guide:
https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Updating-Mastodon-Guide.md

it just doesn't cover this specific case because it was a edge case bug
introduced in the most recent update.

**Comment by WNYmathGuy** [comment]
Thanks @nightpool I'm still not running yet. One suspicious error I saw during install was...
```
yarn install v1.7.0
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/6] Linking dependencies...
[5/6] Building fresh packages...
[6/6] Cleaning modules...
Done in 49.61s.
```
... when I look at my Ruby Gem's list, I have fsevents v. 0.1.1, but no upgrades seem available. I assumed that wasn't a critical failure.

So I wish I knew what was going wrong or how to find out. Got a list of diagnostic commands I could run somewhere? Could that database update command have been my problem? Also, my `mastodon-sidekiq.service` and `mastodon-web.service` services never actually start running. Their set to run at boot but never are running, just `mastodon-streaming.service` is running.

**Comment by WNYmathGuy** [comment]
And this could be just me, but that cron job [Remote media attachment cache cleanup](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md#remote-media-attachment-cache-cleanup) has never worked for my Ubuntu-based instance. I tried working on it today. Thought I was making progress but didn't score the goal. Just kept reading error messages, searching for solutions, trying them reading the new error messages, and so on. Last attempt was to be in the live directory and just run `bundle exec rake mastodon:media:remove_remote` to see if it would work. It didn't, but I had a beautiful array of unintelligible error messages.

**Comment by WNYmathGuy** [comment]
So that `modified:   public/favicon-dev.ico` and `modified:   public/favicon.ico` worry I had was unfounded. I rolled back to the original favicons, the error about them is gone, but I still have a non-working Mastodon instance with no useful diagnostic hints to go by.
