### ISSUE TITLE
Understanding Mastodon - email

### ISSUE THREAD

**Issue by kyzh** [tootsuite/documentation#66]

**Comment by kyzh** [comment]
I have some conceptual diagram and logical flow already.
I'd also like to cover the different option to configure SMTP, what is going on undet the hood.
It could cover related topic like best practise (spf,dkim, etc)

What is the best way to contribute? 
Create a complete new folder with the images and readme?

**Comment by wxcafe** [comment]
imo this is out of the scope of this project. Hosting email is a vast and complicated subject, and this project is only the documentation for Mastodon.
