### ISSUE TITLE
Feature request: IFTTT Mastodon Service

### ISSUE THREAD

**Issue by mdehollander** [tootsuite/documentation#670]
It would be nice to have Mastodon as a service on IFTTT: https://platform.ifttt.com/

Then it would be possible to automatically toot from an RSS feed for example.

**Comment by mdehollander** [comment]
Thanks for your reply and the information. This is really good to know and I fully understand why this is problematic. Hearing about the commercial activities of IFTTT, I start to think to spend time to use open source alternatives like Huginn for this purpose. But here there is the same problem with federated netowrks: https://github.com/huginn/huginn/issues/353#issuecomment-367944724

**Comment by ellotheth** [comment]
Possibly this should be an issue on [the project repository](https://github.com/tootsuite/mastodon/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc), not the docs?
