### ISSUE TITLE
 [Feature Request] Documentation about filter needs to be added 

### ISSUE THREAD

**Issue by GambaJo** [tootsuite/documentation#704]
I can set content filters in the settings. It would be nice, if there is a guide, how to use this filters.
Especially what does the options mean? The descriptions are very confusing.
![10-09-_2018_14-53-57](https://user-images.githubusercontent.com/1378907/45298633-66dea300-b509-11e8-857b-ef423abfc75f.jpg)

**Comment by nightpool** [comment]
I can't read German, so it's hard for me to tell if the options are
confusing because they're confusing, or because of a bad localization.

either way, if the options are confusing we should fix the options, not
write documentation about it
