### ISSUE TITLE
automated or silent install of mastodon setup

### ISSUE THREAD

**Issue by pexdata** [tootsuite/documentation#707]
Is there a way to automate or silently install mastodon from a pre-created response file? 
The following command from the guide: https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Docker-Guide.md

docker-compose run --rm web bundle exec rake mastodon:setup

is interactive. I would like to run this non-interactively by reading a response file or something similar.
I am new to the ruby/rake - may be there is a simple way to do this or somebody already done this.
Appreciate any pointers. I did some searching on github and the web but didn't find anything.

**Comment by nightpool** [comment]
mastodon:setup is only for interactively generating a set of production environment variables. If you already have a set of production environment variables you want to use, just use those.

**Comment by ashleyhull-versent** [comment]
I've built an 99% automated deployment...  you could follow the general steps I've completed to get your instance online without any interactive elements.

plus the new tootctl cli will allow for more automation of the admin account etc etc.

https://github.com/tootsuite/mastodon/pull/8477
