### ISSUE TITLE
How to get an access token with 2FA enabled?

### ISSUE THREAD

**Issue by esttorhe** [tootsuite/documentation#72]
Hi there, first of all, great project and great work with the documentation.

I have a question:
I was trying to get an access token but couldn't for the life of me make it happen (kept getting a `302` asking me to sign in).

After some time trying different approaches it occurred to me to disable `2FA` and that resulted in a success.

I went back to the documentation but couldn't find how to retrieve an access token with `2FA` enabled.

Would it be possible to get an explanation on how to accomplish this?

I would gladly improve the docs with a `PR` with the explanation given here (if there's no trace of this in the current documentation).

Thanks 🙇

**Comment by dariusk** [comment]
Hi, the process outlined here works just fine with 2FA enabled, as long as you are logged in to the account in your web browser that you want to get an access token for:

https://tinysubversions.com/notes/mastodon-bot/

**Comment by esttorhe** [comment]
Thanks @dariusk, the problem is that I'm creating a framework in swift that doesn't know about a web browser and could be used in a headless server. Hence me asking if there's an API to handle 2FA. 

Maybe the server could respond with a specific code and there's another API available to validate the entered code?

**Comment by Gargron** [comment]
The end user is not supposed to pass credentials through 3rd party apps. *Especially* the 2FA token. You'll have to use the OAuth 2 authorization flow.

**Comment by esttorhe** [comment]
Thanks for the answer @Gargron.
I'll dig later this week on the documentation about the `OAuth2` flow.

I'll close this issue now since it is clear there's no way to achieve what I asked originally.
