### ISSUE TITLE
E: Sub-process /usr/bin/dpkg returned an error code (1)

### ISSUE THREAD

**Issue by escrowbangla** [tootsuite/documentation#721]
![screenshot from 2018-09-25 22-21-54](https://user-images.githubusercontent.com/43319382/46028421-5e45b980-c112-11e8-8535-d5deb161771c.png)
I was trying to install nginx into ubuntu 16.04
when I try this command sudo apt install nginx then tarminal reply
sayem@cli:~/app$ sudo apt install nginx
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nginx is already the newest version (1.10.3-0ubuntu0.16.04.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
2 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up nginx-core (1.10.3-0ubuntu0.16.04.2) ...
Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.
invoke-rc.d: initscript nginx, action "start" failed.
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since মঙ্গল 2018-09-25 22:28:03 +06; 6ms ago
  Process: 9976 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=1/FAILURE)
  Process: 9973 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=0/SUCCESS)

সেপ্টে 25 22:28:01 cli nginx[9976]: nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
সেপ্টে 25 22:28:02 cli nginx[9976]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
সেপ্টে 25 22:28:02 cli nginx[9976]: nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
সেপ্টে 25 22:28:02 cli nginx[9976]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
সেপ্টে 25 22:28:02 cli nginx[9976]: nginx: [emerg] bind() to [::]:80 failed (98: Address already in use)
সেপ্টে 25 22:28:03 cli nginx[9976]: nginx: [emerg] still could not bind()
সেপ্টে 25 22:28:03 cli systemd[1]: nginx.service: Control process exited, code=exited status=1
সেপ্টে 25 22:28:03 cli systemd[1]: Failed to start A high performance web server and a reverse proxy server.
সেপ্টে 25 22:28:03 cli systemd[1]: nginx.service: Unit entered failed state.
সেপ্টে 25 22:28:03 cli systemd[1]: nginx.service: Failed with result 'exit-code'.
dpkg: error processing package nginx-core (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of nginx:
 nginx depends on nginx-core (>= 1.10.3-0ubuntu0.16.04.2) | nginx-full (>= 1.10.3-0ubuntu0.16.04.2) | nginx-light (>= 1.10.3-0ubuntu0.16.04.2) | nginx-extras (>= 1.10.3-0ubuntu0.16.04.2); however:
  Package nginx-core is not configured yet.
  Package nginx-full is not installed.
  Package nginx-light is not installed.
  Package nginx-extras is not installed.
 nginx depends on nginx-core (<< 1.10.3-0ubuntu0.16.04.2.1~) | nginx-full (<< 1.10.3-0ubuntu0.16.04.2.1~) | nginx-light (<< 1.10.3-0ubuntu0.16.04.2.1~) | nginx-extras (<< 1.10.3-0ubuntu0.16.04.2.1~); however:
  Package nginx-core is not configured yet.
  Package nginx-full is not installed.
  Package nginx-light is not installed.
  Package nginx-extras is not installed.

dpkg: error processing package nginx (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
                                                                                                          Errors were encountered while processing:
 nginx-core
 nginx
E: Sub-process /usr/bin/dpkg returned an error code (1)
sayem@cli:~/app$

**Comment by nightpool** [comment]
this error does not seem to be related to mastodon. It looks like dpkg is
failing to install nginx-core for some reason. I would suggest
investigating that reason before trying to install mastodon further.
