### ISSUE TITLE
LDAP Filters

### ISSUE THREAD

**Issue by Linneya** [tootsuite/documentation#730]
Hi, 

I've tried 4 times to activate LDAP auth and I am stuck.
I've tried to search in the documentation and the actual [LDAP page](https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Enabling-LDAP-login.md) show everything about LDAP but the LDAP Filter.

I guess some peoples are stuck like me or have simply given up the idea of using Mastodon.

I think it will be useful to put some examples of ( or maybe a total explanation about) the LDAP Filter in order to make Mastodon Installation easier in company ecosystem.

Thank you for reading.

**Comment by Linneya** [comment]
UPDATE: I have browse across the repository and find the class which handle the LDAP Connexion. I learned bit about Ruby and apparently the LDAP_SEARCH_FILTER syntax rely on the format() method of the Kernel.rb file. [Documentation](https://apidock.com/ruby/Kernel/format)

Even if i know that i'm unable to figure out my mistakes.

My LDAP_SEARCH_FILTER look like below:

`LDAP_SEARCH_FILTER="(|(uid=%{uid})(mail=%{email}))"`

Maybe i'm still missing something.

**Comment by astro** [comment]
Just for the record, what worked for me was this: `(&(objectclass=person)(|(%{uid}=%{email})(%{mail}=%{email})))`
