### ISSUE TITLE
Resources needed page

### ISSUE THREAD

**Issue by Gargron** [tootsuite/documentation#74]
One of the items lists Sidekiq params as "5 threads, DB_POOL=10". That is a waste of 5 database connections, because 5 threads will use only 5 connections. `-c` should always equal `DB_POOL`.

Also, the median traffic in/out between the two listed instances is too drastically different - i am assuming because the number of *active* users is different. I think the table should list daily active users or number of nginx connections, instead of total users. Otherwise the metrics are not very useful.

**Comment by wolfteeth** [comment]
I'd like to see the expected resources for running with Docker. Are the requirements similar? Higher?

**Comment by wxcafe** [comment]
The median traffic was so different because of a unit error ^^
And yeah, 5 threads / db_pool 10 is wasteful, tagging @ProgVal about this.
We could add daily nginx connections yeah.

**Comment by ProgVal** [comment]
Why is it wasteful?

**Comment by wxcafe** [comment]
> because 5 threads will use only 5 connections

**Comment by ProgVal** [comment]
oops, I should have read the initial message.
I used to have DB_POOL=5, but I had errors related to not being able to open a connection, or something like that

**Comment by ProgVal** [comment]
This one:

```
daemon.log.2.gz:Apr  5 19:14:27 ruby bundle[811]: 2017-04-05T17:14:27.167Z 811 TID-oxfmii68g WARN: ActiveRecord::ConnectionTimeoutError: could not obtain a connection from the pool within 5.000 seconds (waited 5.000 seconds); all pooled connections were in use
daemon.log.2.gz:Apr  5 19:14:27 ruby bundle[811]: 2017-04-05T17:14:27.167Z 811 TID-oxfmii68g WARN: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:202:in `block in wait_poll'
daemon.log.2.gz:Apr  5 19:14:27 ruby bundle[811]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:193:in `loop'
daemon.log.2.gz:Apr  5 19:14:27 ruby bundle[811]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:193:in `wait_poll'
daemon.log.2.gz:Apr  5 19:14:27 ruby bundle[811]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:154:in `internal_poll'
daemon.log.2.gz:Apr  5 19:14:27 ruby bundle[811]: /home/mastodon-code/mastodon/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:278:in `internal_poll'
```
