### ISSUE TITLE
URLs to documentation items changed.

### ISSUE THREAD

**Issue by tastytea** [tootsuite/documentation#743]
The URL `https://docs.joinmastodon.org/methods/timelines/streaming#event-types` changed into `https://docs.joinmastodon.org/methods/timelines/streaming/#event-types-a-idevent-typesa`, for example. Can the anchors be changed back to the old values? I'd like to be able to hyperlink to individual types from my library documentation.

**Comment by trwnh** [comment]
nb this is going to be really hard to do dynamically. gitbook used to do this automatically, so effectively these kinds of issues will have to be pointed out wherever they are found.
