### ISSUE TITLE
tootctl documentation doesn't display long options correctly.

### ISSUE THREAD

**Issue by rixx** [tootsuite/documentation#747]
The tootctl documentation displays `--` as `–` if not wrapped in code blocks, so adminstrators can't just copy the command line flags from the tables.

You can see the behaviour [here](https://docs.joinmastodon.org/admin/tootctl/) in all the tables. I'm not sure why this happens, since the source file does properly wrap the command line flags inside the tables.

**Comment by rixx** [comment]
I can't replicate the behaviour with the Hugo version available to me, hugo 0.62.2 – but this version is also in use in the [docker image used in the gitlab.ci](https://hub.docker.com/repository/docker/monachus/hugo), unless you've cached the image somehow?

**Comment by trwnh** [comment]
#745 should have fixed this by encasing all options in backticks / code blocks.

**Comment by rixx** [comment]
Is fixed now, so it seems the docs just lagged a bit behind master.
