### ISSUE TITLE
Update for 3.1

### ISSUE THREAD

**Issue by Gargron** [tootsuite/documentation#754]
- [x] Update Node version in installation instructions from 8 to 10
- [x] Add bookmarks REST API
- [ ] Add announcements REST API
- [ ] Add `follow_request` notification type in REST API
- [ ] Add `S3_OVERRIDE_PATH_STYLE` environment variable
- [ ] Add `S3_OPEN_TIMEOUT` environment variable
- [ ] Add `LDAP_MAIL` environment variable
- [ ] Add `LDAP_UID_CONVERSION_ENABLED` environment variable
- [x] Add `--remote-only` option to `tootctl emoji purge`
- [x] Add `tootctl media remove-orphans`
- [x] Add `tootctl media lookup`
- [x] Add discoverable to accounts in REST API
- [ ] Change `last_status_at` to be a date, not datetime in REST API

**Comment by trwnh** [comment]
i already did some things pre-emptively while working on the docs:

- bookmarks api https://docs.joinmastodon.org/methods/accounts/bookmarks/
- `tootctl emoji purge --remote-only` https://docs.joinmastodon.org/admin/tootctl/#emoji-purge
- `tootctl media remove-orphans` https://docs.joinmastodon.org/admin/tootctl/#media-remove-orphans
- `tootctl media lookup` https://docs.joinmastodon.org/admin/tootctl/#media-lookup
- discoverable api https://docs.joinmastodon.org/entities/account/#discoverable
