### ISSUE TITLE
Using IFTTT with Mastodon

### ISSUE THREAD

**Issue by bmann** [tootsuite/documentation#77]
I hope it's OK to use issues here to make documentation. I'm not sure where else this should live right now.

You can use IFTTT and a user's Atom feed to trigger actions from Mastodon posts to other systems. I made this [example applet that posts to my Twitter account if I include the keyword share in my post](https://ifttt.com/applets/52784438d-if-new-feed-item-matches-share-from-https-mastodon-frontierfoundry-co-users-boris-atom-then-post-a-tweet-to-bmann)

To post from other systems into Mastodon will need something like the IFTTT webhook system. I found this example https://gist.github.com/austinhuang0131/3846a66790ecc240ec470229b4318cdf/

If we can figure out the format that Mastodon takes to it's API endpoint, then we can potentially also automate posting INTO your mastodon feed (but I think that will also require an API key or similar?)

**Comment by wxcafe** [comment]
I don't use IFTTT but if someone does and wants to write the doc please feel free to open a PR 👍

**Comment by bmann** [comment]
OK, I'll see about doing a PR for documenting the Atom feed part.

@wxcafe maybe a "How To" or "Extended Use Cases" folder for this sort of thing?

**Comment by wxcafe** [comment]
Using-Mastodon/{Misc,Advanced}.md?

**Comment by bmann** [comment]
I expect that there will be a lot of "how do you do ... ?" with lots of systems. e.g. Reading mastodon user feeds with Feedly, Zapier, etc. etc.

Individual files will make pull requests and edits easier.

**Comment by nclm** [comment]
If it can help to write yours, I did a note about this a few days ago: http://probablement.net/txt/toottotweet

**Comment by wxcafe** [comment]
Then let's make Using-Mastodon/Advanced/IFTTT.md?

**Comment by bmann** [comment]
@wxcafe sounds good.

@nclm great, we don't have to write up, we can just refer to your post! Thanks for sharing!

**Comment by arthurlacoste** [comment]
The IFTTT atom parsing don't seems working anymore. Somebody use it this week ?

**Comment by bmann** [comment]
Working for me.

**Comment by arthurlacoste** [comment]
I found it's don't worked for me, I used an hashtag to filter toot I want to tweet (like "#tw"), and this don't work anymore. But another triggering keywork can work (like "!tw"). Now, IFTTT work fine.
