### ISSUE TITLE
PHP library

### ISSUE THREAD

**Issue by metbril** [tootsuite/documentation#79]
Is a link to any of these of any use for the documentation?

https://github.com/TheCodingCompany/MastodonOAuthPHP

https://github.com/phediverse/mastodon-rest

https://github.com/yks118/Mastodon-api-php

**Comment by sull** [comment]
Stumbled on this one too:

[https://framagit.org/MaxKoder/TootoPHP](https://framagit.org/MaxKoder/TootoPHP)

**Comment by dariusk** [comment]
Closing this, fixed in #197.
