### ISSUE TITLE
Please document  http signature changes in security pages

### ISSUE THREAD

**Issue by wmurphyrd** [tootsuite/documentation#822]
**updated after tracking down issue**
Hello, I've received an [issue report](https://github.com/wmurphyrd/guppe/issues/28) that Masoton 3.2.1 servers are refusing my POSTs from gup.pe with message `Mastodon requires the Digest header to be signed when doing a POST request`

Current documentation at https://docs.joinmastodon.org/spec/security/#http appears to be out of date

Could you update the page so I know exactly what is required now?

**Comment by wmurphyrd** [comment]
Looks like my issue is not limited to secure mode after all, but I would still appreciate this documentation

**Comment by ThibG** [comment]
The documentation change in 34fab9a9ff34bd02403782c8754e3afb2fea9066 is welcome, but it doesn't solve the issue at hand.
https://docs.joinmastodon.org/spec/security/#http-sign should be updated to say that Mastodon requires the following (pseudo-)headers:
- `Date` or `(created)`
- `Host`
- `(request-target)`
- `Digest` if it's a `POST` request
