### ISSUE TITLE
Encoding of status content not defined / explained

### ISSUE THREAD

**Issue by Sciss** [tootsuite/documentation#884]
https://docs.joinmastodon.org/methods/statuses/

This lacks any description of what to expect in `status`. Apparently the toot is wrapped as HTML, using `<p>` and `</p>`. From this, I infer I should decode HTML entities. But I see usage of `&apos` which is [not an HTML entity](https://stackoverflow.com/questions/3989083/html-entity-decoding-in-java-apostrophe) and thus Apache Commons Text doesn't handle it via `StringEscapeUtils.unescapeHtml4`. I can run it additionally through `unescapeXml`, but the whole thing seems weird and underspecified. Any pointers?

**Comment by nightpool** [comment]
Your information is out of date. `apos;` is an HTML named character reference since html5, and is included in the current living standard: https://html.spec.whatwg.org/multipage/named-characters.html#named-character-references

**Comment by Gargron** [comment]
https://docs.joinmastodon.org/client/guidelines/#formatting

**Comment by Sciss** [comment]
I see. Well, Apache Commons doesn't have HTML 5 decode AFAICS...

Note that the docs still do not say to decode HTML 5 entities. So this issue should I either be resolved (by documenting) or re-opened...
